Update script for OS X

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -41,7 +41,7 @@ matrix:
     - os: osx
       compiler: gcc
   allow_failures:
-      - os: osx
+    - os: osx
 
 # Whitelist branches to avoid testing branches
 branches:
@@ -49,23 +49,43 @@ branches:
     - master
 
 before_install:
-  - if [ $CC == gcc ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=gcc-7; fi
-  - export SDE_BIN=sde
-  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ $(uname -m) = x86_64 ]; then export SDE_BIN=sde64; fi
+  - |
+    if [[ $CC == gcc ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
+      export CC=gcc-7
+      export SDE_BIN=sde
+    fi
+    if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ $(uname -m) = x86_64 ]; then
+      export CC=clang
+      export SDE_BIN=sde64
+    fi
 
 install:
-  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo sysctl kernel.yama.ptrace_scope=0; fi
-  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget -q ${SDE_URL}; fi
-  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xvf ${SDE_ARCHIVE}.tar.bz2; fi
-  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_ARCHIVE}; fi
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget -q ${SDE_OSX_URL}; fi
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tar xvf ${SDE_OSX_ARCHIVE}.tar.bz2; fi
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_OSX_ARCHIVE}; fi
+  - |
+    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
+      sudo sysctl kernel.yama.ptrace_scope=0
+      wget -q ${SDE_URL}
+      tar xvf ${SDE_ARCHIVE}.tar.bz2
+      export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_ARCHIVE}
+    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]
+      wget -q ${SDE_OSX_URL}
+      tar xvf ${SDE_OSX_ARCHIVE}.tar.bz2
+      export PATH=${PATH}:${TRAVIS_BUILD_DIR}/${SDE_OSX_ARCHIVE}
+    fi
 
 script:
-  - $CC -Wall cpuid.c -o cpuid-sha.exe
-  - $CC -Wall -DTEST_MAIN=1 -msha -msse4 $BUILD_SOURCE -o test.exe
-  - if ./cpuid-sha.exe -q; then ./test.exe; else $SDE_BIN -- ./test.exe; fi
+  - "$CC" -Wall cpuid.c -o cpuid-sha.exe
+  - "$CC" -Wall -DTEST_MAIN=1 -msse4.2 -msha $BUILD_SOURCE -o test.exe
+  - |
+    echo "SDE_BIN: $SDE_BIN"
+    if [[ -z $(command -v "$SDE_BIN") ]]; then
+      echo "Cannot locate $SDE_BIN"
+      [[ "$0" = "${BASH_SOURCE[0]}" ]] && exit 1 || return 1
+    fi
+    if ./cpuid-sha.exe -q; then
+      ./test.exe
+    else
+      "$SDE_BIN" -- ./test.exe
+    fi
 
 # matrix:
 #  allow_failures:
